### ISSUE TITLE
3D LJ

### ISSUE THREAD

**Issue by symmy596** [symmy596/Advanced_Practical_Chemistry_Teaching#13]
Steve has a tutorial for Lenard Jones particles in 3D using DL_POLY. Can it be factored in or too much effort?
Find and upload

**Comment by arm61** [comment]
My plan was to use it as the starting off point for the intro to md stuff. Basically use what he had written for that. But do the examples in 2D (easier to visualise). He said he would email me the tutorial but I guess has forgotten

**Comment by symmy596** [comment]
Uploaded to course/week_1. 

Closing the issue now
