### ISSUE TITLE
Week 1 assessment 

### ISSUE THREAD

**Issue by symmy596** [symmy596/Advanced_Practical_Chemistry_Teaching#14]
Steve thinks there should be some form of assessment for week 1. In his experience students can fight back a bit if they are working on something that ultimately will not have any impact on their grade. 

My thoughts - Could they write a 1 page method covering MD based purely on the week 1 pylj tutorial?

**Comment by arm61** [comment]
I had actually factored in assessment. But my plan would be that there is no actually assessment. They just fill in the blanks on the notebook and have a demonstrator check it over. Essentially low effort feedback-only

**Comment by arm61** [comment]
I am going to close this and add it to the week 1 issue
