### ISSUE TITLE
Rewrite course instructions

### ISSUE THREAD

**Issue by arm61** [symmy596/Advanced_Practical_Chemistry_Teaching#9]

**Comment by arm61** [comment]
Is this referring to the https://github.com/symmy596/Advanced_Practical_Chemistry_Teaching/blob/master/introductions/scp_Computing_script.pdf file?

**Comment by symmy596** [comment]
Yes. 
I think it would be better if we structured it such that each week has a separate lab manual explaining that weeks exercise, learning outcomes, what will be assessed, what they will need etc.
We do however need a document that deals with an overall course view. Basically a rewrite of this https://github.com/symmy596/Advanced_Practical_Chemistry_Teaching/blob/master/introductions/Briefing_document_diffusion.pdf

**Comment by arm61** [comment]
No worries, I reckon the best way to do this would be to write the overview last. By then we will know what the whole course involves.

**Comment by arm61** [comment]
@symmy596 to delete the https://github.com/symmy596/Advanced_Practical_Chemistry_Teaching/blob/master/introductions/Briefing_document_diffusion.pdf

**Comment by arm61** [comment]
I have deleted this so this is being closed @symmy596. reopen if I am wrong about the reason for closing.
